// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

#ifndef PROTOBUF_hello_2eproto_INCLUDED
#define PROTOBUF_hello_2eproto_INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_hello_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsHelloWorldImpl();
void InitDefaultsHelloWorld();
void InitDefaultsHelloArrayImpl();
void InitDefaultsHelloArray();
inline void InitDefaults() {
  InitDefaultsHelloWorld();
  InitDefaultsHelloArray();
}
}  // namespace protobuf_hello_2eproto
namespace hello {
class HelloArray;
class HelloArrayDefaultTypeInternal;
extern HelloArrayDefaultTypeInternal _HelloArray_default_instance_;
class HelloWorld;
class HelloWorldDefaultTypeInternal;
extern HelloWorldDefaultTypeInternal _HelloWorld_default_instance_;
}  // namespace hello
namespace google {
namespace protobuf {
template<> ::hello::HelloArray* Arena::Create< ::hello::HelloArray>(Arena*);
template<> ::hello::HelloWorld* Arena::Create< ::hello::HelloWorld>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace hello {

// ===================================================================

class HelloWorld : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hello.HelloWorld) */ {
 public:
  HelloWorld();
  virtual ~HelloWorld();

  HelloWorld(const HelloWorld& from);

  inline HelloWorld& operator=(const HelloWorld& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HelloWorld(HelloWorld&& from) noexcept
    : HelloWorld() {
    *this = ::std::move(from);
  }

  inline HelloWorld& operator=(HelloWorld&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HelloWorld& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HelloWorld* internal_default_instance() {
    return reinterpret_cast<const HelloWorld*>(
               &_HelloWorld_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(HelloWorld* other);
  friend void swap(HelloWorld& a, HelloWorld& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HelloWorld* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<HelloWorld>(NULL);
  }

  HelloWorld* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<HelloWorld>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HelloWorld& from);
  void MergeFrom(const HelloWorld& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HelloWorld* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string str = 2;
  bool has_str() const;
  void clear_str();
  static const int kStrFieldNumber = 2;
  const ::std::string& str() const;
  void set_str(const ::std::string& value);
  #if LANG_CXX11
  void set_str(::std::string&& value);
  #endif
  void set_str(const char* value);
  void set_str(const char* value, size_t size);
  ::std::string* mutable_str();
  ::std::string* release_str();
  void set_allocated_str(::std::string* str);

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // optional int32 opt = 3;
  bool has_opt() const;
  void clear_opt();
  static const int kOptFieldNumber = 3;
  ::google::protobuf::int32 opt() const;
  void set_opt(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:hello.HelloWorld)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_str();
  void clear_has_str();
  void set_has_opt();
  void clear_has_opt();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr str_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 opt_;
  friend struct ::protobuf_hello_2eproto::TableStruct;
  friend void ::protobuf_hello_2eproto::InitDefaultsHelloWorldImpl();
};
// -------------------------------------------------------------------

class HelloArray : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hello.HelloArray) */ {
 public:
  HelloArray();
  virtual ~HelloArray();

  HelloArray(const HelloArray& from);

  inline HelloArray& operator=(const HelloArray& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HelloArray(HelloArray&& from) noexcept
    : HelloArray() {
    *this = ::std::move(from);
  }

  inline HelloArray& operator=(HelloArray&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HelloArray& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HelloArray* internal_default_instance() {
    return reinterpret_cast<const HelloArray*>(
               &_HelloArray_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(HelloArray* other);
  friend void swap(HelloArray& a, HelloArray& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HelloArray* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<HelloArray>(NULL);
  }

  HelloArray* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<HelloArray>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HelloArray& from);
  void MergeFrom(const HelloArray& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HelloArray* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .hello.HelloWorld helloWorld = 1;
  int helloworld_size() const;
  void clear_helloworld();
  static const int kHelloWorldFieldNumber = 1;
  ::hello::HelloWorld* mutable_helloworld(int index);
  ::google::protobuf::RepeatedPtrField< ::hello::HelloWorld >*
      mutable_helloworld();
  const ::hello::HelloWorld& helloworld(int index) const;
  ::hello::HelloWorld* add_helloworld();
  const ::google::protobuf::RepeatedPtrField< ::hello::HelloWorld >&
      helloworld() const;

  // @@protoc_insertion_point(class_scope:hello.HelloArray)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::hello::HelloWorld > helloworld_;
  friend struct ::protobuf_hello_2eproto::TableStruct;
  friend void ::protobuf_hello_2eproto::InitDefaultsHelloArrayImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HelloWorld

// required int32 id = 1;
inline bool HelloWorld::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HelloWorld::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HelloWorld::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HelloWorld::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 HelloWorld::id() const {
  // @@protoc_insertion_point(field_get:hello.HelloWorld.id)
  return id_;
}
inline void HelloWorld::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:hello.HelloWorld.id)
}

// required string str = 2;
inline bool HelloWorld::has_str() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HelloWorld::set_has_str() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HelloWorld::clear_has_str() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HelloWorld::clear_str() {
  str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_str();
}
inline const ::std::string& HelloWorld::str() const {
  // @@protoc_insertion_point(field_get:hello.HelloWorld.str)
  return str_.GetNoArena();
}
inline void HelloWorld::set_str(const ::std::string& value) {
  set_has_str();
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hello.HelloWorld.str)
}
#if LANG_CXX11
inline void HelloWorld::set_str(::std::string&& value) {
  set_has_str();
  str_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hello.HelloWorld.str)
}
#endif
inline void HelloWorld::set_str(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_str();
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hello.HelloWorld.str)
}
inline void HelloWorld::set_str(const char* value, size_t size) {
  set_has_str();
  str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hello.HelloWorld.str)
}
inline ::std::string* HelloWorld::mutable_str() {
  set_has_str();
  // @@protoc_insertion_point(field_mutable:hello.HelloWorld.str)
  return str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HelloWorld::release_str() {
  // @@protoc_insertion_point(field_release:hello.HelloWorld.str)
  clear_has_str();
  return str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HelloWorld::set_allocated_str(::std::string* str) {
  if (str != NULL) {
    set_has_str();
  } else {
    clear_has_str();
  }
  str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), str);
  // @@protoc_insertion_point(field_set_allocated:hello.HelloWorld.str)
}

// optional int32 opt = 3;
inline bool HelloWorld::has_opt() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HelloWorld::set_has_opt() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HelloWorld::clear_has_opt() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HelloWorld::clear_opt() {
  opt_ = 0;
  clear_has_opt();
}
inline ::google::protobuf::int32 HelloWorld::opt() const {
  // @@protoc_insertion_point(field_get:hello.HelloWorld.opt)
  return opt_;
}
inline void HelloWorld::set_opt(::google::protobuf::int32 value) {
  set_has_opt();
  opt_ = value;
  // @@protoc_insertion_point(field_set:hello.HelloWorld.opt)
}

// -------------------------------------------------------------------

// HelloArray

// repeated .hello.HelloWorld helloWorld = 1;
inline int HelloArray::helloworld_size() const {
  return helloworld_.size();
}
inline void HelloArray::clear_helloworld() {
  helloworld_.Clear();
}
inline ::hello::HelloWorld* HelloArray::mutable_helloworld(int index) {
  // @@protoc_insertion_point(field_mutable:hello.HelloArray.helloWorld)
  return helloworld_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::hello::HelloWorld >*
HelloArray::mutable_helloworld() {
  // @@protoc_insertion_point(field_mutable_list:hello.HelloArray.helloWorld)
  return &helloworld_;
}
inline const ::hello::HelloWorld& HelloArray::helloworld(int index) const {
  // @@protoc_insertion_point(field_get:hello.HelloArray.helloWorld)
  return helloworld_.Get(index);
}
inline ::hello::HelloWorld* HelloArray::add_helloworld() {
  // @@protoc_insertion_point(field_add:hello.HelloArray.helloWorld)
  return helloworld_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::hello::HelloWorld >&
HelloArray::helloworld() const {
  // @@protoc_insertion_point(field_list:hello.HelloArray.helloWorld)
  return helloworld_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace hello

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_hello_2eproto_INCLUDED
